### ISSUE TITLE
EC2 and S3?

### ISSUE THREAD

**Issue by marick** [jkakar/aws-elixir#15]
It seems that EC2 and S3 are missing from the generated modules. Was that intentional? (If so, might be good to update the README to note which parts of AWS are not supported.)

**Comment by jkakar** [comment]
Thanks for reaching out!

They're on my todo list.  AWS services implement one of several
protocols, such as `json`, `rest-json`, `rest-xml`, `query`, etc.  So
far, [aws-codegen](https://github.com/jkakar/aws-codegen) only has support for generating clients for
services that use the `json` and `rest-json` protocol.  The [full list
of supported services](https://github.com/jkakar/aws-codegen/blob/master/lib/aws_codegen.ex#L2-L35) is described in the code generator (and I agree,
putting this list in the README is a good idea).

The issue with the remaining protocols is that they produce and
consume XML.  I need to work out how to convert XML into a map and
then back again.  I don't think it's a really difficult problem, I
just haven't made the time to focus on it.  I've been spending the
cycles I have for this project working on [aws-erlang](https://github.com/jkakar/aws-erlang) and getting it to
feature parity with the Elixir code here.  I suspect I'll end up
focusing the implementation in Erlang and converting aws-elixir into a
wrapper around aws-erlang.

**Comment by marick** [comment]
I'd offer to help, but I'm too much an Elixir newbie. I'll look forward to your new library and see what I can do with `erlcloud` in the meantime.

**Comment by heri16** [comment]
Still awaiting S3 support for basic GetObject

**Comment by jkakar** [comment]
@heri16 Sorry, I haven't had time to give this project attention for quite awhile.  If you have time to help, someone needs to sort out the XML-to-map and back again conversion issues.

**Comment by heri16** [comment]
I beleive erlang OTP stack has a built-in XML library.
