### ISSUE TITLE
Need HTTPoison

### ISSUE THREAD

**Issue by chetmancini** [jkakar/aws-elixir#32]
It may be helpful to clarify that the httpoison application needs to be setup to avoid error messages like this from the example:

```
* (exit) exited in: :gen_server.call(:hackney_manager, {:new_request, #PID<0.263.0>, #Reference<0.0.5.143>, {:client, :undefined, :hackney_dummy_metrics, :hackney_ssl_transport, 'kinesis.us-east-1.amazonaws.com', 443, "kinesis.us-east-1.amazonaws.com", [], nil, nil, nil, true, :hackney_pool, 5000, false, 5, false, 5, nil, nil, nil, :undefined, :start, nil, :normal, false, false, false, :undefined, false, nil, :waiting, nil, 4096, "", [], :undefined, nil, nil, nil, nil, :undefined, nil}}, :infinity)
    ** (EXIT) no process
    (stdlib) gen_server.erl:212: :gen_server.call/3
             src/hackney_manager.erl:66: :hackney_manager.init_request/1
             src/hackney_manager.erl:56: :hackney_manager.new_request/1
             src/socket/hackney_connect.erl:183: :hackney_connect.socket_from_pool/4
             src/socket/hackney_connect.erl:36: :hackney_connect.connect/5
             src/hackney.erl:321: :hackney.request/5
             lib/httpoison/base.ex:395: HTTPoison.Base.request/9
             lib/aws/kinesis.ex:534: AWS.Kinesis.request/4
```

**Comment by jkakar** [comment]
Hmm, that shouldn't be an issue because `httpoison` is [explicitly listed in the list of dependent applications](https://github.com/jkakar/aws-elixir/blob/master/mix.exs#L22), right?

**Comment by jkakar** [comment]
Did you call `Application.ensure_all_started(:aws)` in your IEx console or make sure that `:aws` is in the list of dependent applications in your app?

**Comment by chetmancini** [comment]
@jkakar ok, I'm extremely new to Elixir. didn't realize I needed the `ensure_all_started` in my Phoenix app console.

**Comment by jkakar** [comment]
@chetmancini You generally shouldn't need it if your app is correctly configured.  You should make sure that `:aws` is in the list of applications in your `mix.exs`, as in:

```elixir
  def application do
    [applications: [:aws, :logger]]
  end
```

After `:aws` is there the dependencies will be auto-loaded and started when you run `iex -S mix`.
