### ISSUE TITLE
Support for Timex 2.x

### ISSUE THREAD

**Issue by boydm** [jkakar/aws-elixir#40]
Would be great for aws-elixir to carry a dependency on Timex 2.x instead of 1.x.

**Comment by jkakar** [comment]
Thanks for the hint @boydm!  Timex is upgraded to 2.x and is [published to Hex](https://hex.pm/packages/aws/0.0.11) alongside a [number of other changes](https://github.com/jkakar/aws-elixir/blob/master/CHANGELOG.md#v0011---2016-04-21).

**Comment by boydm** [comment]
Wow. Thank you for the fast turn-around!

**Comment by jkakar** [comment]
My pleasure.  It's nice to know people might be using these clients. :)
