### ISSUE TITLE
Current version of poison incompatible with new version of Phoenix

### ISSUE THREAD

**Issue by dfinninger** [jkakar/aws-elixir#42]
```
Failed to use "poison" (version 2.2.0) because
  aws (version 0.0.11) requires ~> 1.0
  phoenix (version 1.2.0) requires ~> 1.5 or ~> 2.0
  Locked to 2.2.0 in your mix.lock
```

For new projects with Phoenix, I can't use this library unless I downgrade Phoenix.

**Comment by jkakar** [comment]
I've just pushed [v0.0.12](https://hex.pm/packages/aws/0.0.12) to bump `poison` from `~1.0` to `~1.5 or ~2.0`.  Please let me know if you have any issues using it with the latest version of Phoenix.  Thanks for this report!
