### ISSUE TITLE
Using aws-elixir in a rebar3 Erlang project

### ISSUE THREAD

**Issue by derek121** [jkakar/aws-elixir#46]
I'm experienced with building Erlang with rebar3, but am inexperienced with Elixir and mix. I want to use aws-elixir from an Erlang project, but apparently rebar3 doesn't support Elixir dependencies. So I thought I'd just build aws-elixir manually, and then include the path to the .beam's when I start my Erlang VM (as mentioned at http://www.rebar3.org/discuss/55841dbbafccfd0d00fcb1f8)

My question is about the generated beam files in _build/dev/consolidated/ and _build/dev/lib/ I'd guess that I'd have to include _build/dev/consolidated/*beam and _build/dev/lib/*/ebin/ in my VM codepath, unless there was some easier way. 

Thanks for any recommendations.

**Comment by jkakar** [comment]
Thanks for reaching out!  I've never actually tried to use an Elixir dependency in an Erlang project.  Have you looked at jkakar/aws-erlang?  It doesn't provide the same set of clients (yet) that are available for Elixir, but if what you need is there, that'll be easier to integrate.

**Comment by derek121** [comment]
No, I actually had not seen that- thanks for pointing out! I wound up forking https://github.com/erlcloud/erlcloud today and going ahead and adding the one or two functions of the Firehose API that I needed, but this is good to see as well. Nice...
