### ISSUE TITLE
Example fails to run

### ISSUE THREAD

**Issue by indiejames** [jkakar/aws-elixir#59]
Language version: Elixir 1.4.2
OS: macOS Sierra 10.12.3

I created a sample project using mix and added {:aws, "~> 0.5.0"} to the project dependencies.
I launched a REPL using iex -S mix.
I created a client structure using
```elixir
client = %AWS.Client{access_key_id: access_key_id,
                     secret_access_key: secret_access_key,
                     region: "us-east-1",
                     endpoint: "amazonaws.com"}
```

Where `access_key_id` and `secret_access_key` were bound to the appropriate values.

Then I tried to execute the demo in the README

```elixir
{:ok, result, resp} = AWS.Kinesis.list_streams(client, %{})
``` 

I get the following error and stack trace:

** (exit) exited in: :gen_server.call(:hackney_manager, {:new_request, #PID<0.1614.0>, #Reference<0.0.8.8801>, {:client, :undefined, {:metrics_ng, :metrics_dummy}, :hackney_ssl, 'kinesis.us-east-1.amazonaws.com', 443, "kinesis.us-east-1.amazonaws.com", [], nil, nil, nil, true, :hackney_pool, 5000, false, 5, false, 5, nil, nil, nil, {0, {:dict, 0, 16, 16, 8, 80, 48, {[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []}, {{[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []}}}}, :undefined, :start, nil, :normal, false, false, false, :undefined, false, nil, :waiting, nil, 4096, "", [], :undefined, nil, nil, nil, nil, :undefined, nil}}, :infinity)
    ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
    (stdlib) gen_server.erl:212: :gen_server.call/3
             /Users/jnorton/Elixir/rekog/deps/hackney/src/hackney_manager.erl:65: :hackney_manager.init_request/1
             /Users/jnorton/Elixir/rekog/deps/hackney/src/hackney_manager.erl:55: :hackney_manager.new_request/1
             /Users/jnorton/Elixir/rekog/deps/hackney/src/hackney_connect.erl:185: :hackney_connect.socket_from_pool/4
             /Users/jnorton/Elixir/rekog/deps/hackney/src/hackney_connect.erl:37: :hackney_connect.connect/5
             /Users/jnorton/Elixir/rekog/deps/hackney/src/hackney.erl:330: :hackney.request/5
             lib/httpoison/base.ex:432: HTTPoison.Base.request/9
             lib/aws/kinesis.ex:594: AWS.Kinesis.request/4

**Comment by indiejames** [comment]
I figured out that I needed to add :httpoison to the applications in mix.deps. I'm going to leave this issue open as I think you should mention this in the README.md.

**Comment by jkakar** [comment]
Thanks for the report. Have you tried adding `:aws` to the `:applications` list in `mix.exs`? I believe that should work correctly.

**Comment by jkakar** [comment]
I pushed a small change to the README to describe how to start the console to run the example, but I suspect that isn't the issue you're seeing. Please let me know if I've misunderstood your report.
