### ISSUE TITLE
Auto-update once upstream (Go SDK) is updated

### ISSUE THREAD

**Issue by gjmveloso** [jkakar/aws-elixir#60]
Hi @jkakar,

I've just landed on this repo and I'm wondering if having some kind of auto-update once a release on [Go upstream project](https://github.com/aws/aws-sdk-go/tree/release/models/apis) is planned/feasible?

Thanks

**Comment by jkakar** [comment]
That's a great idea! I've considered it, but not done anything about it. If this is something you'd be interested in working on, I'd love to see it happen. At this stage, I don't really have the time/bandwidth to work on it, though.

**Comment by gjmveloso** [comment]
Count me in, @jkakar.
I'll try to make it happen.

**Comment by jkakar** [comment]
Awesome, thank you @gjmveloso!

**Comment by gjmveloso** [comment]
Closing this as the generation portion is under [jkakar/aws-codegen](https://github.com/jkakar/aws-codegen) instead of this repo.
